add_subdirectory(atmosphere)
add_subdirectory(cloud_ref)
add_subdirectory(cloud_ref_2)
add_subdirectory(clouds_legacy)
add_subdirectory(fluid)
add_subdirectory(fractal_2d)
add_subdirectory(gltf_viewer)
add_subdirectory(ocean)
add_subdirectory(pbr_furnace)
add_subdirectory(planet)
add_subdirectory(procedural_terrain_legacy)
add_subdirectory(terrain_lab_legacy)
