#include <cstdio>
#include <exception>

void test_run_config_parses_png_output_path();
void test_camera_2d_pans_zooms_and_reports_view();
void test_camera_2d_clamps_scale();
void test_camera_3d_builds_projection_and_view_from_world_transform();
void test_camera_3d_orbit_helper_matches_existing_cube_view();
void test_camera_manager_entity_destroy_retires_attached_components();
void test_camera_manager_rejects_duplicate_and_stale_entity_edits();
void test_camera_manager_updates_keep_epoch_local_snapshots();
void test_camera_managers_publish_2d_and_3d_camera_snapshots();
void test_capture_queue_encodes_png_with_inline_executor();
void test_capture_queue_propagates_encoding_errors();
void test_command_pool_exposes_command_buffer_ownership();
void test_compute_helpers_describe_pipeline_and_layout_setup();
void test_deferred_destruction_queue_retires_completed_tickets();
void test_descriptor_helpers_describe_layout_pool_and_writes();
void test_descriptor_set_info_copies_bindings_and_aggregates_pool_sizes();
void test_descriptor_set_allocate_info_describes_multiple_sets();
void test_dynamic_rendering_describes_attachment_setup();
void test_engine_creates_independent_scenes();
void test_engine_destroys_owned_scenes_and_rejects_foreign_scenes();
void test_engine_exposes_render_resource_registry();
void test_engine_created_scenes_validate_render_resource_handles();
void test_engine_exposes_project_runtime_services();
void test_engine_reuses_project_frame_for_same_timing();
void test_entity_handles_track_null_reserved_and_alive_states();
void test_entity_manager_concurrent_reservations_are_unique();
void test_entity_manager_invalidates_generations_and_defers_reuse();
void test_entity_manager_rolls_back_reserved_entities();
void test_file_io_round_trips_binary_bytes();
void test_frame_clock_tracks_delta_elapsed_and_index();
void test_frame_resources_expose_slot_based_contract();
void test_frame_stats_publish_window_title_metrics();
void test_frame_ticket_issuer_returns_monotonic_tickets();
void test_headless_png_host_validates_capture_shape();
void test_image_io_writes_rgba_png();
void test_image_transitions_describe_layout_barriers();
void test_input_state_accumulates_cursor_and_scroll_per_frame();
void test_input_state_ignores_unknown_inputs();
void test_input_state_tracks_key_and_button_edges();
void test_pan_zoom_2d_controller_pans_and_zooms_from_input();
void test_pointer_drag_tracks_active_cursor_and_accumulated_delta();
void test_inline_executor_runs_jobs_immediately();
void test_job_system_runs_jobs_and_propagates_errors();
void test_job_system_shutdown_rejects_new_jobs();
void test_math_helpers_match_vulkan_projection_conventions();
void test_math_quaternion_helpers_match_rotation_matrices();
void test_orbit_controller_tracks_rotation_drag_pause_and_reset();
void test_orbit_controller_updates_from_input_snapshot();
void test_pipeline_helpers_describe_dynamic_graphics_pipeline_setup();
void test_project_context_exposes_async_runtime_services();
void test_project_runtime_contract_supports_lifecycle_shape();
void test_project_runtime_adapter_exposes_context_and_retirement();
void test_project_runtime_adapter_reuses_frame_for_same_timing();
void test_project_runtime_services_create_project_frames_and_context();
void test_render_context_exposes_explicit_frame_boundary();
void test_frame_slot_defaults_to_single_frame_slot();
void test_frame_slot_wraps_frame_indices();
void test_frame_slot_rejects_invalid_slots();
void test_frame_uniform_buffer_config_describes_host_visible_uniform_storage();
void test_frame_uniform_buffer_contract_is_slot_based_and_move_only();
void test_render_plan_builds_sorted_3d_draw_packets_with_material_metadata();
void test_render_plan_rejects_stale_resource_handles();
void test_render_resource_registry_tracks_handle_lifetime_and_labels();
void test_render_resource_handles_are_hashable_keys();
void test_render_resource_registry_round_trips_mesh_and_material_info();
void test_render_resource_table_resolves_move_only_resources_by_handle();
void test_renderable_manager_emits_multiple_visible_primitives();
void test_renderable_manager_entity_destroy_retires_attached_components();
void test_renderable_manager_publishes_3d_packets_from_scene_read_view();
void test_renderable_manager_rejects_invalid_edits_and_missing_transforms();
void test_renderable_manager_skips_invisible_renderables_without_transform();
void test_renderable_manager_updates_keep_epoch_local_snapshots();
void test_resource_helpers_describe_device_local_upload_and_depth_setup();
void test_scene_edit_queue_publishes_reserved_entities_on_commit();
void test_scene_failed_commit_rolls_back_reserved_entities();
void test_scene_read_views_defer_destroyed_entity_reuse_until_release();
void test_spirv_io_reads_aligned_words();
void test_spirv_io_rejects_misaligned_byte_count();
void test_stable_slot_store_rejects_stale_handles_without_moving_other_slots();
void test_transform_manager_2d_publishes_parented_world_matrices();
void test_transform_manager_3d_publishes_parented_world_matrices();
void test_transform_manager_read_views_keep_epoch_local_snapshots();
void test_transform_manager_rejects_invalid_parenting_and_child_destroy();
void test_transform_manager_reparenting_preserves_local_transform();
void test_transform_2d_builds_affine_matrix();
void test_transform_3d_builds_affine_matrix();
void test_transform_3d_matches_existing_cube_rotation_order();
void test_transfer_helpers_describe_texture_and_readback_paths();
void test_upload_queue_drains_in_submission_order();
void test_upload_queue_owns_payload_until_drain();
void test_windowed_host_config_defaults_to_two_frame_slots();

int main() {
    try {
        test_run_config_parses_png_output_path();
        test_camera_2d_pans_zooms_and_reports_view();
        test_camera_2d_clamps_scale();
        test_camera_3d_builds_projection_and_view_from_world_transform();
        test_camera_3d_orbit_helper_matches_existing_cube_view();
        test_camera_managers_publish_2d_and_3d_camera_snapshots();
        test_camera_manager_updates_keep_epoch_local_snapshots();
        test_camera_manager_entity_destroy_retires_attached_components();
        test_camera_manager_rejects_duplicate_and_stale_entity_edits();
        test_capture_queue_encodes_png_with_inline_executor();
        test_capture_queue_propagates_encoding_errors();
        test_command_pool_exposes_command_buffer_ownership();
        test_compute_helpers_describe_pipeline_and_layout_setup();
        test_deferred_destruction_queue_retires_completed_tickets();
        test_descriptor_helpers_describe_layout_pool_and_writes();
        test_descriptor_set_info_copies_bindings_and_aggregates_pool_sizes();
        test_descriptor_set_allocate_info_describes_multiple_sets();
        test_dynamic_rendering_describes_attachment_setup();
        test_engine_exposes_project_runtime_services();
        test_engine_reuses_project_frame_for_same_timing();
        test_engine_creates_independent_scenes();
        test_engine_destroys_owned_scenes_and_rejects_foreign_scenes();
        test_engine_exposes_render_resource_registry();
        test_engine_created_scenes_validate_render_resource_handles();
        test_entity_handles_track_null_reserved_and_alive_states();
        test_entity_manager_invalidates_generations_and_defers_reuse();
        test_entity_manager_rolls_back_reserved_entities();
        test_entity_manager_concurrent_reservations_are_unique();
        test_file_io_round_trips_binary_bytes();
        test_frame_clock_tracks_delta_elapsed_and_index();
        test_frame_resources_expose_slot_based_contract();
        test_frame_stats_publish_window_title_metrics();
        test_frame_ticket_issuer_returns_monotonic_tickets();
        test_headless_png_host_validates_capture_shape();
        test_image_io_writes_rgba_png();
        test_image_transitions_describe_layout_barriers();
        test_input_state_tracks_key_and_button_edges();
        test_input_state_accumulates_cursor_and_scroll_per_frame();
        test_input_state_ignores_unknown_inputs();
        test_pointer_drag_tracks_active_cursor_and_accumulated_delta();
        test_pan_zoom_2d_controller_pans_and_zooms_from_input();
        test_inline_executor_runs_jobs_immediately();
        test_job_system_runs_jobs_and_propagates_errors();
        test_job_system_shutdown_rejects_new_jobs();
        test_math_helpers_match_vulkan_projection_conventions();
        test_math_quaternion_helpers_match_rotation_matrices();
        test_orbit_controller_tracks_rotation_drag_pause_and_reset();
        test_orbit_controller_updates_from_input_snapshot();
        test_pipeline_helpers_describe_dynamic_graphics_pipeline_setup();
        test_project_context_exposes_async_runtime_services();
        test_project_runtime_contract_supports_lifecycle_shape();
        test_project_runtime_adapter_reuses_frame_for_same_timing();
        test_project_runtime_adapter_exposes_context_and_retirement();
        test_project_runtime_services_create_project_frames_and_context();
        test_render_context_exposes_explicit_frame_boundary();
        test_frame_slot_defaults_to_single_frame_slot();
        test_frame_slot_wraps_frame_indices();
        test_frame_slot_rejects_invalid_slots();
        test_frame_uniform_buffer_config_describes_host_visible_uniform_storage();
        test_frame_uniform_buffer_contract_is_slot_based_and_move_only();
        test_render_plan_builds_sorted_3d_draw_packets_with_material_metadata();
        test_render_plan_rejects_stale_resource_handles();
        test_render_resource_registry_tracks_handle_lifetime_and_labels();
        test_render_resource_handles_are_hashable_keys();
        test_render_resource_registry_round_trips_mesh_and_material_info();
        test_render_resource_table_resolves_move_only_resources_by_handle();
        test_renderable_manager_publishes_3d_packets_from_scene_read_view();
        test_renderable_manager_emits_multiple_visible_primitives();
        test_renderable_manager_skips_invisible_renderables_without_transform();
        test_renderable_manager_updates_keep_epoch_local_snapshots();
        test_renderable_manager_entity_destroy_retires_attached_components();
        test_renderable_manager_rejects_invalid_edits_and_missing_transforms();
        test_resource_helpers_describe_device_local_upload_and_depth_setup();
        test_stable_slot_store_rejects_stale_handles_without_moving_other_slots();
        test_scene_edit_queue_publishes_reserved_entities_on_commit();
        test_scene_failed_commit_rolls_back_reserved_entities();
        test_scene_read_views_defer_destroyed_entity_reuse_until_release();
        test_spirv_io_reads_aligned_words();
        test_spirv_io_rejects_misaligned_byte_count();
        test_transform_manager_2d_publishes_parented_world_matrices();
        test_transform_manager_3d_publishes_parented_world_matrices();
        test_transform_manager_reparenting_preserves_local_transform();
        test_transform_manager_read_views_keep_epoch_local_snapshots();
        test_transform_manager_rejects_invalid_parenting_and_child_destroy();
        test_transform_2d_builds_affine_matrix();
        test_transform_3d_builds_affine_matrix();
        test_transform_3d_matches_existing_cube_rotation_order();
        test_transfer_helpers_describe_texture_and_readback_paths();
        test_upload_queue_owns_payload_until_drain();
        test_upload_queue_drains_in_submission_order();
        test_windowed_host_config_defaults_to_two_frame_slots();
    } catch (const std::exception& error) {
        std::fprintf(stderr, "cubey_core_tests: %s\n", error.what());
        return 1;
    }
}
