#pragma once

#include <cubey/core/run_config.h>

#include <filesystem>
#include <span>
#include <string_view>

namespace cubey {

enum class ConfigOptionType {
    Bool,
    Int,
    UInt32,
    UInt64,
    Float,
    String,
    Path,
    Enum,
};

enum class RunConfigOptionId {
    Title,
    Width,
    Height,
    Frames,
    Fps,
    OutputPath,
    DebugView,
    Headless,
    Validation,
    RequireValidation,
    PrintFrameStats,
    CaptureMode,
    GridWidth,
    GridHeight,
    GridDepth,
    ProfileOutput,
    ProfileWarmupFrames,
    ProfileDiagnostics,
    ProfileDiagnosticInterval,
    GltfInput,
    GltfAnimationIndex,
    GltfAnimationSpeed,
    GltfAnimationPaused,
    PbrEnvironment,
    PbrEnvironmentSource,
    PbrIblIntensity,
    PbrEnvironmentRotation,
    PbrExposure,
    OceanMapSize,
    OceanFieldPrecision,
    OceanSurfaceMode,
    OceanCameraPreset,
    OceanPlanetRadiusScale,
    OceanCurvatureStartRatio,
    OceanCurvatureEndRatio,
    OceanCurvatureStrength,
    OceanCascade,
    OceanSpectralDomains,
    OceanTerrainFields,
    OceanWireOverlay,
    OceanWireOpacity,
    PlanetScalePreset,
    PlanetRadius,
    PlanetAtmosphereHeight,
    PlanetCameraAltitude,
    PlanetCameraOrbitSpin,
    PlanetCameraSurfacePitch,
    PlanetCameraSurfaceYaw,
    PlanetCameraSurfaceLook,
    PlanetPatchesPerFace,
    PlanetPatchResolution,
    PlanetMaxLodLevel,
    PlanetLodTargetEdge,
    PlanetLodHysteresis,
    PlanetLocalDetailLodLevels,
    PlanetLocalDetailCells,
    PlanetLocalDetailOuterExtent,
    PlanetLocalDetail,
    PlanetLocalDetailHeight,
    PlanetLocalDetailScale,
    PlanetWireOverlay,
    PlanetSkirts,
    PlanetSkirtDepthScale,
    PlanetTerrain,
    PlanetTerrainHeightScale,
    PlanetTerrainNoiseScale,
    PlanetTerrainMidDetailStrength,
    PlanetTerrainFineDetailStrength,
    PlanetTerrainFineDetailScale,
    PlanetTerrainSeed,
    PlanetSeaLevel,
    PlanetBathymetryDepthScale,
    PlanetShorelineWidth,
    PlanetAtmosphereHazeStrength,
    PlanetAtmosphereHazeStart,
    PlanetAtmosphereHazeEnd,
    PlanetAtmosphereAerialStrength,
    PlanetDayOfYear,
    PlanetTimeHours,
    PlanetTimeSpeed,
    PlanetTimePaused,
    PlanetCameraMode,
    PlanetAtmosphereMode,
    TerrainSeed,
    TerrainCellSize,
    TerrainSeaLevel,
    TerrainLandExtent,
    TerrainCoastNoise,
    TerrainRelief,
    TerrainRidges,
    TerrainValleys,
    TerrainWaterSurface,
    TerrainLabSlicePreset,
    TerrainLabCameraPreset,
    TerrainLabNoiseSource,
    AtmospherePreset,
    AtmosphereTimeOfDayMode,
    AtmosphereNightSkyMode,
    AtmosphereMilkyWayLayer,
    AtmosphereSunElevation,
    AtmosphereSunAzimuth,
    AtmosphereCameraAltitude,
    AtmosphereCameraYawOffset,
    AtmosphereCameraPitchOffset,
    AtmosphereRayleighScale,
    AtmosphereMieScale,
    AtmosphereOzoneScale,
    AtmosphereTimeHours,
    AtmosphereDayOfYear,
    AtmosphereLatitude,
    AtmosphereSunAzimuthOffset,
    AtmosphereTimeSpeed,
    AtmosphereTimePaused,
    AtmosphereAutoExposure,
    AtmosphereExposureBias,
    AtmosphereTwilightStrength,
    AtmosphereTwilightHorizonWarmth,
    AtmosphereStarIntensity,
    AtmosphereStarDensity,
    AtmosphereMilkyWayIntensity,
    AtmosphereMilkyWayContrast,
    AtmosphereLightPollution,
    AtmosphereMilkyWayVariation,
    AtmosphereMoonIntensity,
    AtmosphereMoonlightIntensity,
    AtmosphereMoonPhaseOffset,
    AtmosphereMoonSizeScale,
    AtmosphereMoon,
    AtmosphereReferenceGeometry,
    CloudEnabled,
    CloudDebugView,
    CloudCameraMode,
    CloudQuality,
    CloudWeatherPreset,
    CloudCacheFrames,
    CloudCacheTextureSize,
    CloudRenderPath,
    CloudDensityModel,
    CloudResolveMode,
    CloudBackgroundMode,
    CloudDistanceMode,
    CloudOrbitRepresentation,
    CloudPlanetRadius,
    CloudCameraAltitude,
    CloudBottomAltitude,
    CloudTopAltitude,
    CloudCoverage,
    CloudDensity,
    CloudWeatherScale,
    CloudShapeDomain,
    CloudFootprintFilterStrength,
    CloudEdgeSoftness,
    CloudEdgeDetailFade,
    CloudEdgeResolveStrength,
    CloudVerticalShearFraction,
    CloudWindSpeed,
    CloudShadowStrength,
    CloudHorizonStrength,
    CloudWeatherFronts,
    CloudWeatherCells,
    CloudWeatherStreaks,
    CloudWeatherSoftness,
    CloudWeatherInfluence,
    CloudDetailErosion,
    CloudAmbientStrength,
    CloudDirectStrength,
    CloudPhaseStrength,
    CloudFinalContrast,
    CloudFinalSaturation,
    CloudResolveStrength,
    CloudResolveRadius,
    CloudHorizonGlowStrength,
    CloudSunGlareStrength,
    CloudSamplingMode,
    CloudJitterStrength,
    CloudOrbitTransitionStart,
    CloudOrbitTransitionEnd,
    CloudFarShellStart,
    CloudFarShellEnd,
    CloudFarShellStrength,
    CloudOrbitDetailStrength,
    CloudOrbitDensityScale,
    CloudOrbitFill,
    CloudOrbitMotionStrength,
    CloudOrbitShellExtinction,
    CloudTemporal,
    CloudLocalVolume,
    CloudHorizonLayer,
    SmokeInjectors,
    SmokePressureIterations,
    SmokePressureSolver,
    SmokeDyeDecay,
    SmokeVelocityDecay,
    SmokeInjectorRadius,
    SmokeInjectorForce,
    SmokeInjectorPropulsion,
    SmokeInjectorOrbitRadius,
    SmokeInjectorOrbitRadiusSpread,
    SmokeInjectorOrbitAngularSpeed,
    SmokeInjectorOrbitAngularSpeedSpread,
    SmokeInjectorOrbitPhaseSpread,
    SmokeVorticity,
    PyroShadowGridWidth,
    PyroShadowGridHeight,
    PyroShadowGridDepth,
    PyroShadowSteps,
    PyroShadowUpdateInterval,
    PyroSources,
    PyroSourceHeight,
    PyroSourceRadius,
    PyroSourceForce,
    PyroSoot,
    PyroTemperature,
    PyroFuel,
    PyroBuoyancy,
    PyroIgnitionTemperature,
    PyroBurnRate,
    PyroHeatOutput,
    PyroSootYield,
    PyroExpansion,
    PyroFlameCooling,
    PyroShredding,
    PyroTurbulence,
    PyroObstacleHeight,
    PyroObstacleRadius,
    PyroExplosionInterval,
    PyroExplosionDuration,
    PyroExplosionBoost,
    Water2DTransfer,
    Water2DTransferLimit,
    Water2DHose,
    Water2DDrain,
    Water2DWave,
    Water3DTransfer,
    Water3DTransferLimit,
    Water3DP2GMode,
    Water3DHose,
    Water3DDrain,
    Water3DRain,
    Water3DWave,
    Water3DWhitewater,
};

struct ConfigOptionRange {
    bool has_min = false;
    bool has_max = false;
    double min = 0.0;
    double max = 0.0;
};

struct ConfigEnumChoices {
    const std::string_view* values = nullptr;
    std::size_t count = 0;
};

struct ConfigOptionDescriptor {
    RunConfigOptionId id;
    std::string_view path;
    std::string_view cli_name;
    std::string_view negative_cli_name;
    std::string_view label;
    std::string_view group_path;
    std::string_view help;
    ConfigOptionType type = ConfigOptionType::String;
    ConfigOptionRange range{};
    ConfigEnumChoices enum_choices{};
};

struct RunConfigFileApplyResult {
    bool output_path_set = false;
};

[[nodiscard]] std::span<const ConfigOptionDescriptor> run_config_option_descriptors();
[[nodiscard]] const ConfigOptionDescriptor* find_run_config_option(std::string_view path);
[[nodiscard]] const ConfigOptionDescriptor*
find_run_config_option_by_cli_name(std::string_view cli_name);
[[nodiscard]] bool config_option_has_choice(const ConfigOptionDescriptor& option,
                                            std::string_view value);
void set_run_config_option_from_string(RunConfig& config, const ConfigOptionDescriptor& option,
                                       std::string_view value);
void set_run_config_option_from_string(RunConfig& config, std::string_view path,
                                       std::string_view value);
RunConfigFileApplyResult apply_run_config_file(RunConfig& config,
                                               const std::filesystem::path& path);
void write_run_config_template(const RunConfig& config, const std::filesystem::path& path);

} // namespace cubey
