#ifndef CUBEY_CLOUD_WEATHER_COMMON_GLSL
#define CUBEY_CLOUD_WEATHER_COMMON_GLSL

const float CLOUD_WEATHER_PERLIN_SCALE = 100.0;
const float CLOUD_WEATHER_COVERAGE_SCALE = CLOUD_WEATHER_PERLIN_SCALE * 0.95;
const float CLOUD_WEATHER_COVERAGE_FREQUENCY = 0.8;
const float CLOUD_WEATHER_FEATURE_DENSITY =
    CLOUD_WEATHER_COVERAGE_SCALE * CLOUD_WEATHER_COVERAGE_FREQUENCY;
const float CLOUD_WEATHER_TYPE_SCALE = CLOUD_WEATHER_PERLIN_SCALE * 3.0;
const float CLOUD_WEATHER_TYPE_FREQUENCY = 0.3;

const int CLOUD_DENSITY_REF_DENSITY = 0;
const int CLOUD_DENSITY_PROCEDURAL = 1;
const int CLOUD_DENSITY_CLOUD_REF_COMPATIBLE = 2;

#endif
